version: 2

sources:
  - name: staging
    schema: main
    tables:
      - name: yellow_tripdata
      - name: green_tripdata

  - name: raw
    schema: main
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata_2019_11
      - name: fhv_tripdata_2019_02
